### ISSUE TITLE
Clarifications on variable declarations

### ISSUE THREAD

**Issue by dbaelde** [akiss/akiss#2]
The following script is accepted by akiss (branch master):

```
channels C;
r = in(C,Y);
equivalentct? r and r;
```

There is no `var` declaration: is that expected? What is the use of that declaration, then?

I'm wondering about this because, in the xor branch, not declaring a variable results in a `Not_found` error raised by the `Maude` module during saturation. This is really obscure, and actually hard to debug when using lwt, which yields useless backtraces (am I missing a tool here?). I'll improve it soon, once I understand better the intended use of the `var` declaration in vanilla akiss.

**Comment by steve-kremer** [comment]
Hi David,

I just fixed this issue (in the master branch).

Declaration of variables was only verified when parsing terms. Inputs
however contained variable identifiers (rather than terms) and they were
not checked.

Best,
Steve

> The following script is accepted by akiss (branch master):
> 
> |channels C; r = in(C,Y); equivalentct? r and r; |
> 
> There is no |var| declaration: is that expected? What is the use of that
> declaration, then?
> 
> I'm wondering about this because, in the xor branch, not declaring a
> variable results in a |Not_found| error raised by the |Maude| module
> during saturation. This is really obscure, and actually hard to debug
> when using lwt, which yields useless backtraces (am I missing a tool
> here?). I'll improve it soon, once I understand better the intended use
> of the |var| declaration in vanilla akiss.

**Comment by dbaelde** [comment]
Thanks for the quick reaction! I've merged this into the xor branch, which solves the issue for me.
