### ISSUE TITLE
Dumb treatment of variables in maude parser of xor branch

### ISSUE THREAD

**Issue by dbaelde** [akiss/akiss#3]
The `fullmaude.ml` parser considers that identifiers starting with `P` (among other letters) are variables. It thus issues parse errors when encountering constants such as `PIN` ou `PAN`.

The letters `P` and `Q` are used internally in the xor branch for marked variables. The same variable names are used when talking to Maude.

Of course, this detection of variables is too restrictive. But the code cannot simply lookup the list of declared variables, since the saturation algorithm generates lots of variables without declaring them.

We could either use a smarter naming convention (use prefixes when translating internal identifiers to Maude identifiers) or perhaps simply avoid having to detect variables: after all, they are mostly used to know if we should expect ":Term" after the identifier, and it would not hurt to allow it all the time.

**Comment by steve-kremer** [comment]
This issue has been solved when switching from 'full maude' to 'maude'.
